
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make partition-create'
	@echo
	@echo '	$$ make asset-install'
	@echo
	@echo '	$$ make prototype-install'
	@echo
	@echo '	$$ make config-install'
	@echo


.PHONY: help


install:
	@./install.sh
.PHONY: install


partition-create:
	@./partition-create.sh
.PHONY: partition-create
